"""Project add columns

Revision ID: 418745ba19a2
Revises: 
Create Date: 2024-11-07 15:24:14.733073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '418745ba19a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'projects', ['proyecto_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_solicitud', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('fecha_recepcion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_estimada_conexion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('capacidad', sa.String(length=32), nullable=True))

    with op.batch_alter_table('representantes', schema=None) as batch_op:
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'projects', ['proyecto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('representantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('capacidad')
        batch_op.drop_column('fecha_estimada_conexion')
        batch_op.drop_column('fecha_recepcion')
        batch_op.drop_column('estado_solicitud')

    with op.batch_alter_table('coordinadores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('proyecto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
