"""Added RCA and FRCA fields to Project

Revision ID: cf78bf820751
Revises: 418745ba19a2
Create Date: 2024-11-13 14:50:34.006287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf78bf820751'
down_revision = '418745ba19a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('deleted', sa.SmallInteger(), nullable=True),
    sa.Column('last_modification_date', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rca', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('frca', sa.DateTime(), nullable=True))
        batch_op.alter_column('estado_solicitud',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('estado_solicitud',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               existing_nullable=True)
        batch_op.drop_column('frca')
        batch_op.drop_column('rca')

    op.drop_table('parameters')
    # ### end Alembic commands ###
